export * from './domain/role.entity'
export { ApiRoleRepository } from './infrastructure/role.service'
export { roleActions } from './application/role.actions'
export { RoleEditPageComponent as RoleEditPage } from './interfaces/pages/role-edit-page.component'
export { RoleEffect } from './application/role.effects'
export { roleFeature } from './application/role.feature'
export { RoleListPageComponent as RoleListPage } from './interfaces/pages/role-list-page.component'
export { RoleNewPageComponent as RolePage } from './interfaces/pages/role-new-page.component'
export { type RoleRepository } from './domain/role.repository'
export { roleRoutes } from './role.routes'
export { RoleShowPageComponent as RoleShowPage } from './interfaces/pages/role-show-page.component'
