export * from './domain/dealership.entity'
export { ApiDealershipRepository } from './infrastructure/dealership.service'
export { dealershipActions } from './application/dealership.actions'
export { DealershipEditPageComponent as DealershipEditPage } from './interfaces/pages/dealership-edit-page.component'
export { DealershipEffect } from './application/dealership.effects'
export { dealershipFeature } from './application/dealership.feature'
export { DealershipListPageComponent as DealershipListPage } from './interfaces/pages/dealership-list-page.component'
export { DealershipNewPageComponent as DealershipNewPage } from './interfaces/pages/dealership-new-page.component'
export { type DealershipRepository } from './domain/dealership.repository'
export { dealershipRoutes } from './dealership.routes'
export { DealershipShowPageComponent as DealershipShowPage } from './interfaces/pages/dealership-show-page.component'
